<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data analysis project 12</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Data analysis 12 (1) (1)_files/libs/clipboard/clipboard.min.js"></script>
<script src="Data analysis 12 (1) (1)_files/libs/quarto-html/quarto.js"></script>
<script src="Data analysis 12 (1) (1)_files/libs/quarto-html/popper.min.js"></script>
<script src="Data analysis 12 (1) (1)_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Data analysis 12 (1) (1)_files/libs/quarto-html/anchor.min.js"></script>
<link href="Data analysis 12 (1) (1)_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Data analysis 12 (1) (1)_files/libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Data analysis 12 (1) (1)_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Data analysis 12 (1) (1)_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Data analysis 12 (1) (1)_files/libs/bootstrap/bootstrap-8a79a254b8e706d3c925cde0a310d4f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="Data analysis 12 (1) (1)_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="Data analysis 12 (1) (1)_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Data analysis project 12</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-intro" class="level1">
<h1>Introduction</h1>
<p>Over the years, there has been an increase in the health awareness of the Scottish population, with a fear that the country as a whole is becoming overweight. The body mass index (BMI) is a quick way to measure weight relative to height, and screen for people that are underweight, overweight, or obese.</p>
<p>This report aims to explore changes in BMI trends in Scotland using data from the 2013–2016 Scottish Health Survey. Specifically, we seek to answer the following key questions:</p>
<ol type="1">
<li>Has the BMI in Scotland changed over the given years of the Scottish Health Survey?</li>
<li>Are there any difference inthe BMI distributions by age, gender, socioeconomic status or lifestyle factors?</li>
</ol>
<p>By analyzing this data, we aim to identify patterns that could inform public health strategies and address potential risk factors contributing to obesity.</p>
</section>
<section id="sec-expdata" class="level1">
<h1>Exploratory data analysis</h1>
<section id="data-overview" class="level2">
<h2 class="anchored" data-anchor-id="data-overview">Data Overview</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  Age    Sex               Education Year   BMIgroup
1  48 Female       No qualifications 2016      Obese
2  51   Male        Degree or higher 2016 Overweight
3  48 Female        Degree or higher 2016     Normal
4  16 Female       No qualifications 2016     Normal
5  61   Male Standard grade or equiv 2016     Normal
6  40 Female        Degree or higher 2016     Normal</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 14,017
Columns: 5
$ Age       &lt;int&gt; 48, 51, 48, 16, 61, 40, 43, 40, 39, 45, 18, 29, 36, 37, 78, …
$ Sex       &lt;chr&gt; "Female", "Male", "Female", "Female", "Male", "Female", "Mal…
$ Education &lt;chr&gt; "No qualifications", "Degree or higher", "Degree or higher",…
$ Year      &lt;int&gt; 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, …
$ BMIgroup  &lt;chr&gt; "Obese", "Overweight", "Normal", "Normal", "Normal", "Normal…</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>      Age       Sex Education      Year  BMIgroup 
        0         0         0         0         0 </code></pre>
</div>
</div>
<p>The dataset consists of 14,017 observations with the following columns:</p>
<p><strong>Age</strong>: Age of individuals</p>
<p><strong>Sex</strong>: Gender of individuals (Male/Female)</p>
<p><strong>Education</strong>: Highest educational qualification</p>
<p><strong>Year</strong>: Year of the survey (2013-2016)</p>
<p><strong>BMIgroup</strong>: Weight classification group (e.g., Obese, Overweight, Normal)</p>
</section>
<section id="summary-statistics" class="level2">
<h2 class="anchored" data-anchor-id="summary-statistics">Summary Statistics</h2>
<p>Computing descriptive statistics helps understand the distribution of the data.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Summary Statistics of the Dataset</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Sample_Size</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean_Age</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Median_Age</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Min_Age</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q1_Age</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q3_Age</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Max_Age</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Std_Age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">14017</td>
<td style="text-align: right;">50.84262</td>
<td style="text-align: right;">51</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">65</td>
<td style="text-align: right;">99</td>
<td style="text-align: right;">17.60925</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Key observations from the summary statistics:</p>
<ul>
<li><p>No missing values are detected.</p></li>
<li><p>Age distribution is fairly wide, with a range from young adults to elderly individuals.</p></li>
<li><p>BMI categories contain multiple classifications, which will later be converted into a binary variable for analysis.</p></li>
</ul>
</section>
<section id="identifying-distribution-and-checking-normality" class="level2">
<h2 class="anchored" data-anchor-id="identifying-distribution-and-checking-normality">Identifying Distribution and Checking Normality</h2>
<p>We use a histogram to visualize the distribution of age and assess normality.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Data-analysis-12--1---1-_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The histogram reveals that the age distribution in the dataset is approximately&nbsp;bell-shaped&nbsp;but slightly&nbsp;right-skewed. The majority of individuals fall within the&nbsp;40-60 age range, while younger individuals (&lt;20 years) and older individuals (&gt;80 years) are less represented. The right skew suggests that there are more older individuals in the dataset than younger ones.</p>
</section>
<section id="identifying-outliers" class="level2">
<h2 class="anchored" data-anchor-id="identifying-outliers">Identifying outliers:</h2>
<p>To detect outliers, we use a&nbsp;boxplot&nbsp;to visualize the spread of ages within each&nbsp;</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Data-analysis-12--1---1-_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The boxplot provides a visual summary of the distribution of&nbsp;age across different BMI categories (Normal, Obese, Overweight, and Underweight). Key observations include:</p>
<ul>
<li><p>The&nbsp;median age varies slightly across BMI groups, with individuals classified as overweight and obese tending to be older than those in the normal or underweight categories.</p></li>
<li><p>The&nbsp;interquartile range (IQR)&nbsp;(middle 50% of the data) shows that most individuals are between&nbsp;40 and 70 years old, regardless of BMI classification.</p></li>
<li><p>There are potential outliers, particularly among&nbsp;younger and older individuals, indicating that some individuals outside the usual age range may require further investigation.</p></li>
</ul>
</section>
<section id="creating-a-binary-obesity-classification" class="level2">
<h2 class="anchored" data-anchor-id="creating-a-binary-obesity-classification">Creating a Binary Obesity Classification</h2>
<p>Since we want to analyze obesity prevalence, we create a new binary response variable where:</p>
<ul>
<li><p>Obese = 1</p></li>
<li><p>Not Obese (Normal &amp; Overweight) = 0</p></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
   0    1 
9754 4263 </code></pre>
</div>
</div>
</section>
<section id="bmi-trends-over-time" class="level2">
<h2 class="anchored" data-anchor-id="bmi-trends-over-time">BMI Trends Over Time</h2>
<p>Analyzing how obesity has changed over time using proportions.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Data-analysis-12--1---1-_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Key findings:</p>
<ul>
<li><p>The proportion of obese individuals appears relatively stable over the years.</p></li>
<li><p>A significant proportion of individuals are classified as overweight.</p></li>
</ul>
</section>
<section id="obesity-distribution-by-demographics" class="level2">
<h2 class="anchored" data-anchor-id="obesity-distribution-by-demographics">Obesity Distribution by Demographics</h2>
<section id="by-age-group" class="level3">
<h3 class="anchored" data-anchor-id="by-age-group">By Age Group</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Data-analysis-12--1---1-_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Middle-aged individuals (45-60) have the highest obesity rates.</li>
</ul>
</section>
<section id="by-gender" class="level3">
<h3 class="anchored" data-anchor-id="by-gender">By Gender</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Data-analysis-12--1---1-_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Females exhibit higher obesity rates compared to males.</li>
</ul>
</section>
</section>
</section>
<section id="correlation-analysis" class="level1">
<h1>Correlation Analysis</h1>
<p>Examining the relationship between Age and Obesity.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  obesity$Age and obesity$ObeseBinary
t = 11.804, df = 14015, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.08279939 0.11558340
sample estimates:
       cor 
0.09921832 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Data-analysis-12--1---1-_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The scatter plot illustrates the relationship between age and obesity, where obesity is represented as a binary variable (1= Obese, 0= Not obese). The distribution of points suggest that obesity is present across all ages groups without a strong visual trend. The calculated correlation coefficient of 0.099 indicates a very weak positive relationship, meaning that as age increases, there is only a slight tendency for obesity prevalence to rise.</p>
</section>
<section id="sec-formdata" class="level1">
<h1>Formal data analysis</h1>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Year</th>
<th>Obese proportions</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2013</td>
<td>0.30300569</td>
</tr>
<tr class="even">
<td>2014</td>
<td>0.30181715</td>
</tr>
<tr class="odd">
<td>2015</td>
<td>0.30645161</td>
</tr>
<tr class="even">
<td>2016</td>
<td>0.30536494</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      
       0 1
  2013 3 1
  2014 3 1
  2015 3 1
  2016 3 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared Test for Trend in Proportions

data:  trend_table[, 2] out of rowSums(trend_table) ,
 using scores: 1 2 3 4
X-squared = 0, df = 1, p-value = 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2013 2014 2015 2016</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  trend_table
X-squared = 0, df = 3, p-value = 1</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = obese_binary ~ as.numeric(Year), family = binomial, 
    data = bmi_trends)

Coefficients:
                   Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)      -1.099e+00  1.414e+00  -0.777    0.437
as.numeric(Year) -3.440e-16  5.164e-01   0.000    1.000

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 17.995  on 15  degrees of freedom
Residual deviance: 17.995  on 14  degrees of freedom
AIC: 21.995

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>The analysis into whether the prevalence of obesity in Scotland has changed over the given years of the Scottish Health Survey includes a Chi-squared test for trend, Pearson’s Chi-squared test, and a logistic regression model.</p>
<p>The Chi-squared test for trend examines whether there is a significant trend in obesity prevalence over the years. With a test statistic of X² = 0, df = 1, and a p-value of 1, this suggests no significant trend.</p>
<p>The Pearson’s Chi-squared test compares obesity proportions across years without assuming a trend. With X² = 0, df = 3, and p-value = 1, there is no significant difference in obesity prevalence across years.</p>
<p>The logistic regression model tests whether the year is a significant predictor of obesity. The coefficient for year is -9.132e-16 , with a p-value of 1, indicating no relationship between year and obesity. The Intercept of -1.099 represents the log-odds of obesity in the baseline year.</p>
<p>The Akaike Information Criterion (AIC = 21.995) measures model fit, with lower values indicating better fit. However, since the model finds no effect of year on obesity, this value is less meaningful in this case.</p>
<p>Overall, all statistical tests confirm that obesity prevalence in Scotland has remained unchanged over the given years.</p>
<section id="question-2" class="level3">
<h3 class="anchored" data-anchor-id="question-2">Question 2</h3>
<p>To answer the second question, we use linear regression to find out if age, gender, socio-economic status, or lifestyle factors are significant predictors for obesity.</p>
<p>We start by looking at if age is a significant predictor for a persons BMI group. We are fitting the following linear model:</p>
<p><span class="math display">\[
logit(\pi) = \beta_0 + \beta_1 x_i + \epsilon_i, ~~~~~ \epsilon_i \sim N(0, \sigma^2), ~~~~~ i = 1, ... , 14017
\]</span></p>
<p>Here, <span class="math inline">\(\pi\)</span> is the probability that the individual is obese, <span class="math inline">\(x_i\)</span> is the age of the ith individual, and <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span> are regression coefficients. We are using the logit link function.</p>
<div class="cell" data-warnings="false">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">&nbsp;</td>
<td colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">BM Igroup</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Predictors</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Odds Ratios</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">CI</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">(Intercept)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">4.33</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">3.86&nbsp;–&nbsp;4.86</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Age</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.99</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.99&nbsp;–&nbsp;0.99</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
</tbody>
</table>


</div>
</div>
<p>As seen from the p-value, we can infer that age is a significant predictor for a persons BMI group. As someones age increases by one year, the odds of the person being obese increase by a factor of 0.99.</p>
<p>We now check the assumptions of our model, to find out if the model is valid.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-diagnostics1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-diagnostics1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Data-analysis-12--1---1-_files/figure-html/fig-diagnostics1-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diagnostics1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Diagnostic plots for the age model
</figcaption>
</figure>
</div>
</div>
</div>
<p>There is no issues that can be seen in the posterior predictive check, influential obesvations graph, and the uniformity of resuduals graph. There does appear to be a large amount of points falling outiwth the error bounds in the binned residuals graph. We would expect about 95% of points to fall within the error bounds if the model is true. As there is a large amount of points plotted it is hard to tell if there is 95% within the error bounds, as there may be overlap. However, it appears to be good enough.</p>
<p>We now look at sex to consider if it is significant through fitting the following model:</p>
<p><span class="math display">\[
logit(\pi) = \beta_0 + \beta_1 x_i + \epsilon_i, ~~~~~ \epsilon_i \sim N(0, \sigma^2), ~~~~~ i = 1, ... , 14017
\]</span></p>
<p>Where <span class="math inline">\(x_i\)</span> is an indicator variable taking the value 0 if the individual is a male and the value 1 if the individual is a female.</p>
<div class="cell" data-warnings="false">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">&nbsp;</td>
<td colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">BM Igroup</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Predictors</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Odds Ratios</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">CI</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">(Intercept)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2.44</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2.31&nbsp;–&nbsp;2.57</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Sex [Female]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.89</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.83&nbsp;–&nbsp;0.96</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>0.002</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">R<sup>2</sup> Tjur</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">0.001</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>As seen from table 2, the p-value indicates that sex is a significant predictor at the 5% significance level. Furthermore, the odds ratio for being obese increase by 0.89 for females.</p>
<p>Again, we check our model assumptions to find out if our results are valid.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-diagnostics2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-diagnostics2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Data-analysis-12--1---1-_files/figure-html/fig-diagnostics2-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diagnostics2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Diagnostic plots for the sex model
</figcaption>
</figure>
</div>
</div>
</div>
<p>The plots in figure 2 look good enough. There may be issues with the binned residuals plot, however the issue likely stems from sex being a factor with 2 levels giving us only 2 points.</p>
<p>We now look at education to consider if there is a difference in obesity based on socio-economic factors. We fit the following model:</p>
<p><span class="math display">\[
logit(\pi) = \beta_0 + \beta_1 x_i + \beta_2 x_j + \beta_3 x_k + \beta_4 x_l +\beta_5 x_m + \beta_6 x_n + \epsilon_i, ~~~~~ \epsilon_i \sim N(0, \sigma^2), ~~~~~ i = 1, ... , 14017
\]</span> Where <span class="math inline">\(x_i\)</span> through <span class="math inline">\(x_n\)</span> are indicator variables taking the value 1 if they have that level of education and 0 if they do not. The <span class="math inline">\(\beta_0\)</span> term refers to the referrence level which is having a degree.</p>
<div class="cell" data-warnings="false">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">&nbsp;</td>
<td colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">BM Igroup</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Predictors</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Odds Ratios</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">CI</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">(Intercept)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">3.05</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2.85&nbsp;–&nbsp;3.26</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Education [Higher grade<br>
or equiv]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.84</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.75&nbsp;–&nbsp;0.94</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>0.003</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Education [HNC/D or<br>
equiv]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.72</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.64&nbsp;–&nbsp;0.82</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Education [No<br>
qualifications]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.53</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.48&nbsp;–&nbsp;0.59</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Education [Other school<br>
level]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.60</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.51&nbsp;–&nbsp;0.70</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Education [Standard grade<br>
or equiv]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.67</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.60&nbsp;–&nbsp;0.74</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">R<sup>2</sup> Tjur</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">0.011</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>As seen from table 3, all the levels of education are considered significant predictors of the persons BMI group. The odds of a person being obese is 3.05 for a person with a degree, then increases by 0.53-0.84 depending on qualification level.</p>
<p>Again, we have to check the model assumptions.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-diagnostics3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-diagnostics3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Data-analysis-12--1---1-_files/figure-html/fig-diagnostics3-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diagnostics3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Diagnostic plots for the education model
</figcaption>
</figure>
</div>
</div>
</div>
<p>The interpretation of figure 3 is much like the previous figures. The only graph that leaves cause for concern is the binned residuals graph, but again, becuase it is a factor, it is always going to not work as well as a continuous variable. Thus, the model is appropriate.</p>
</section>
<section id="sec-results" class="level2">
<h2 class="anchored" data-anchor-id="sec-results">Results</h2>
</section>
</section>
<section id="sec-conc" class="level1">
<h1>Conclusions</h1>
<blockquote class="blockquote">
<blockquote class="blockquote">
<blockquote class="blockquote">
<blockquote class="blockquote">
<blockquote class="blockquote">
<blockquote class="blockquote">
<blockquote class="blockquote">
<p>Formal-Analysis-Q2</p>
</blockquote>
</blockquote>
</blockquote>
</blockquote>
</blockquote>
</blockquote>
</blockquote>
<p>From the previous tests, we have seen that age, sex, and education are all significant in the prediction of an individuals BMI group, indicating differences in obesity across these factors. As age increases, the odds of obesity rise. Females have higher odds of being obese than males, and lower education levels are associated with greater odds of obesity.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>